<div class="onestepcheckout-ajax-loader" id="onestepcheckout-review-ajax-loader" style="display:none;"></div>

<div id="checkout-review-load" style="display:block;">
    <?php echo $this->getChildHtml('info') ?>
</div>
<div id="checkout-review-submit">
    <?php echo $this->getChildHtml('agreements') ?>
    <div id="onepage-checkout-shipping-method-additional-load">
        <?php echo $this->getChildHtml('additional') ?>
    </div>
    <div class="buttons-set" id="review-buttons-container">
        <p class="f-left"><?php echo $this->__('Forgot an Item?') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Your Cart') ?></a></p>
        <button type="button" title="<?php echo $this->__('Place Order') ?>" class="button btn-checkout" onclick="review.save();"><span><span><?php echo $this->__('Place Order') ?></span></span></button>
        <span class="please-wait" id="review-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
        </span>
    </div>
    <script type="text/javascript">
    //<![CDATA[
        var review = new Review('onestepcheckout-form', '<?php echo $this->getUrl('checkout/onestep/saveOrder') ?>', $('checkout-agreements'));
    //]]>
    </script>
</div>
