<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Phoenix
 * @package	Phoenix_Vfg
 * @copyright  Copyright (c) 2010 Phoenix Medien GmbH & Co. KG (http://www.phoenix-medien.de)
 */


/**
USAGE:

Simple:

<?php echo $this->getLayout()->createBlock('customer/widget_name')
   ->setObject($this->getAddress())
   ->toHtml() ?>

For checkout/onepage/shipping.phtml:

<?php echo $this->getLayout()->createBlock('customer/widget_name')
   ->setObject($this->getAddress())
   ->setFieldIdFormat('shipping:%s')
   ->setFieldNameFormat('shipping[%s]')
   ->setFieldParams('onchange="shipping.setSameAsBilling(false);"')
   ->toHtml() ?>
*/
?>

<?php if ($this->showPrefix()): ?>
<div>
	<label for="<?php echo $this->getFieldId('prefix')?>"<?php if ($this->isPrefixRequired()) echo ' class="required"' ?>><?php echo $this->__('Prefix') ?><?php if ($this->isPrefixRequired()) echo '<em>*</em>' ?></label>
	<?php if ($this->getPrefixOptions()===false): ?>
	<input type="text" id="<?php echo $this->getFieldId('prefix')?>" name="<?php echo $this->getFieldName('prefix')?>" value="<?php echo $this->htmlEscape($this->getObject()->getPrefix()) ?>" title="<?php echo $this->__('Prefix') ?>" class="ti<?php if ($this->isPrefixRequired()):?> required-entry<?php endif; ?>" <?php echo $this->getFieldParams() ?> />
	<?php else: ?>
		<?php $isFirst=true; ?>
		<?php foreach ($this->getPrefixOptions() as $_option): ?>
			<?php if (!empty($_option)): ?>
	<input id="<?php echo "{$this->getFieldId('prefix')}_$_option"?>" name="<?php echo $this->getFieldName('prefix')?>" type="radio" value="<?php echo $_option?>"<?php if ($this->getObject()->getPrefix()==$_option):?> checked="checked"<?php endif; ?> class="rb<?php if ($this->isPrefixRequired()):?> validate-one-required-by-name<?php endif;?><?php if ($isFirst):?> first<?php endif;?>" <?php echo $this->getFieldParams() ?>/>
	<label for="<?php echo "{$this->getFieldId('prefix')}_$_option"?>" class="radiolabel"><?php echo $this->__($_option)?></label>
				<?php $isFirst=false;?>
			<?php endif; ?>
		<?php endforeach ?>
	<?php endif; ?>
</div>
<?php endif; ?>

<div>
	<label for="<?php echo $this->getFieldId('firstname')?>" class="required"><?php echo $this->__('First Name') ?><em>*</em></label>
	<input type="text" id="<?php echo $this->getFieldId('firstname')?>" name="<?php echo $this->getFieldName('firstname')?>" value="<?php echo $this->htmlEscape($this->getObject()->getFirstname()) ?>" title="<?php echo $this->__('First Name') ?>" class="ti required-entry" <?php echo $this->getFieldParams() ?> />
</div>

<?php if ($this->showMiddlename()): ?>
<div>
	<label for="<?php echo $this->getFieldId('middlename')?>"><?php echo $this->__('M.I.') ?></label>
	<input type="text" id="<?php echo $this->getFieldId('middlename')?>" name="<?php echo $this->getFieldName('middlename')?>" value="<?php echo $this->htmlEscape($this->getObject()->getMiddlename()) ?>" title="<?php echo $this->__('M.I.') ?>" class="ti" <?php echo $this->getFieldParams() ?> />
</div>
<?php endif; ?>

<div>
	<label for="<?php echo $this->getFieldId('lastname')?>" class="required"><?php echo $this->__('Last Name') ?><em>*</em></label>
	<input type="text" id="<?php echo $this->getFieldId('lastname')?>" name="<?php echo $this->getFieldName('lastname')?>" value="<?php echo $this->htmlEscape($this->getObject()->getLastname()) ?>" title="<?php echo $this->__('Last Name') ?>" class="ti required-entry" <?php echo $this->getFieldParams() ?> />
</div>

<?php if ($this->showSuffix()): ?>
<div>
	<label for="<?php echo $this->getFieldId('suffix')?>"<?php if ($this->isSuffixRequired()) echo ' class="required"' ?>><?php echo $this->__('Suffix') ?><?php if ($this->isSuffixRequired()) echo '<em>*</em>' ?></label>
<?php if ($this->getSuffixOptions()===false): ?>
	<input type="text" id="<?php echo $this->getFieldId('suffix')?>" name="<?php echo $this->getFieldName('suffix')?>" value="<?php echo $this->htmlEscape($this->getObject()->getSuffix()) ?>" title="<?php echo $this->__('Suffix') ?>" class="ti<?php if ($this->isSuffixRequired()):?> required-entry<?php endif; ?>" <?php echo $this->getFieldParams() ?> />
<?php else: ?>
	<select id="<?php echo $this->getFieldId('suffix')?>" name="<?php echo $this->getFieldName('suffix')?>" title="<?php echo $this->__('Suffix') ?>" class="sl<?php if ($this->isSuffixRequired()):?> required-entry<?php endif; ?>" <?php echo $this->getFieldParams() ?>>
	<?php foreach ($this->getSuffixOptions() as $_option): ?>
		<option value="<?php echo $_option?>"<?php if ($this->getObject()->getSuffix()==$_option):?> selected="selected"<?php endif; ?>><?php echo $this->__($_option)?></option>
	<?php endforeach ?>
	</select>
<?php endif; ?>
</div>
<?php endif; ?>