<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-cart"><?php echo $this->getHeaderText() ?></h4>
        <div class="form-buttons">
            <button type="button" id="add-inquiry" class="button">
                <span>
                    <span>
                        <?php echo $this->__('Add product') ?>
                    </span>
                </span>
            </button>
        </div>
    </div>
    123123123
    <?php echo $this->getChildHtml() ?>
</div>
