<?php
/**
 * Product criteria template
 *
 * @see Testimonial_MageDoc_Block_Criteria
 */
?>
<?php $collection = $this->getCriteriaCollection() ?>
<?php if (count($collection)): ?>
<h2><?php echo Mage::helper('magedoc')->__('Criteria:') ?></h2>
<div class="product-info-table-wrapper rnd">
    <table class="product-criteria product-info-table">
        <tbody>
            <?php foreach ($collection as $criteria): ?>
                <tr>
                    <td><?php echo $criteria->getCriteria() ?></td> <td><?php echo $criteria->getCriteriaValueText() ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif; ?>