<?php $lookupCollection = $this->getLookupCollection() ?>
<?php if (count($lookupCollection)): ?>
<h2><?php echo Mage::helper('magedoc')->__('Spare part replacements:') ?></h2>
    <div class="product-info-table-wrapper rnd">
        <table class="product-lookup product-info-table">
            <tbody>
                <?php foreach ($lookupCollection as $lookup): ?>
                    <tr>
                        <td>
                            <?php echo $lookup->getBrand() ?>
                        </td>
                        <td class="tr">
                            <?php echo $lookup->getNumber() ?>
                        </td>
                    </tr>
                <?php endforeach;?>
            </tbody>
        </table>
    </div>
<?php endif; ?>