<?php
/**
 * Category layered navigation
 *
 * @see Mage_Catalog_Block_Layer_View
 */
?>
<?php if($this->canShowBlock()): ?>
    <div class="naigation">
        <?php echo $this->getStateHtml() ?>
        <?php if ($this->getLayer()->getState()->getFilters()): ?>
        <!--<div class="actions"><a href="<?php /*echo $this->getClearUrl() */?>"><?php /*echo $this->__('Clear All') */?></a></div>-->
        <?php endif; ?>
        <?php if($this->canShowOptions()): ?>
            <?php $_filters = $this->getFilters() ?>
            <?php foreach ($_filters as $_filter): ?>
            <?php if($_filter->getItemsCount()): ?>
                <?php echo $_filter->getHtml() ?>
                <?php endif; ?>
            <?php endforeach; ?>
        <script type="text/javascript">decorateDataList('narrow-by-list')</script>
        <?php endif; ?>
    </div>
<?php endif; ?>
