<div class="combo-container <?php echo $this->getClass(); ?>" id="<?php echo $this->getContainerId()?>">
    <label><?php echo $this->getLabel() ?></label>
    <input type="text" class="combo-input" autocomplete="off" value="<?php echo $this->getTextValue()?>" name="<?php echo $this->getInputName()?>" <? echo $this->getDisabled() ?> />
    <select class="combo-select" size="<?php echo $this->getSelectSize()?>" name="<?php echo $this->getSelectName()?>" <? echo $this->getDisabled() ?> tabindex="-1">
        <?php // print_r($this->getData()); die;?>
        <?php foreach($this->getValues() as $key => $option):?>
            <? if($this->getValue() == $key):?>
                <option value="<?php echo $key?>" selected="selected"><?php echo $option?></option>
            <? else: ?>
                <option value="<?php echo $key?>"><?php echo $option?></option>                
            <? endif; ?>    
        <?php endforeach;?>
    </select>
</div>
