<h1><?php echo $this->__('Forgot Your Password?') ?></h1>
<p><?php echo $this->__('Please enter your email below and we\'ll send you a new password.') ?></p>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate" class="form">
	<fieldset>
		<div>
			<label for="email_address" class="required"><?php echo $this->__('Email Address') ?><em>*</em></label>
			<input type="text" name="email" alt="email" id="email_address" class="ti required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
		</div>
	<fieldset class="formnavi">
		<button type="button" class="btn btngrey btnback" onclick="javascript:history.back();"><span><?php echo $this->__('Back') ?></span></button>
        <button type="submit" class="btn"><span><?php echo $this->__('Submit') ?></span></button>
    </fieldset>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>