<?php $_inquiry = $this->getinquiry() ?>
<?php $this->setPriceDataObject($_inquiry) ?>
<tr class="border">
    <td><?php echo $_inquiry->getCategory(); ?></td>
    <td><?php echo $_inquiry->getSupplier(); ?></td>
    <td><?php echo $_inquiry->getName(); ?></td>
    <td><?php echo $_inquiry->getSku(); ?></td>
    <td class="a-right">
        <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
            <span class="price-excl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                    <span class="label"><?php echo $this->__('Excl. Tax'); ?>:</span>
                <?php endif; ?>

                <?php if (Mage::helper('weee')->typeOfDisplay($_inquiry, array(0, 1, 4), 'sales', $_inquiry->getStoreId())): ?>
                    <?php
                    echo $this->displayPrices(
                        $_inquiry->getBasePrice()+$_inquiry->getBaseWeeeTaxAppliedAmount()+$_inquiry->getBaseWeeeTaxDisposition(),
                        $_inquiry->getPrice()+$_inquiry->getWeeeTaxAppliedAmount()+$_inquiry->getWeeeTaxDisposition()
                    );
                    ?>
                <?php else: ?>
                    <?php echo $this->displayPrices($_inquiry->getBasePrice(), $_inquiry->getPrice()) ?>
                <?php endif; ?>


                <?php if (Mage::helper('weee')->getApplied($_inquiry)): ?>
                    <br />
                    <?php if (Mage::helper('weee')->typeOfDisplay($_inquiry, 1, 'sales', $_inquiry->getStoreId())): ?>
                        <small>
                        <?php foreach (Mage::helper('weee')->getApplied($_inquiry) as $tax): ?>
                            <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->displayPrices($tax['base_amount'], $tax['amount']); ?></span>
                        <?php endforeach; ?>
                        </small>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_inquiry, 2, 'sales', $_inquiry->getStoreId())): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_inquiry) as $tax): ?>
                            <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $this->displayPrices($tax['base_amount_incl_tax'], $tax['amount_incl_tax']); ?></small></span>
                        <?php endforeach; ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_inquiry, 4, 'sales', $_inquiry->getStoreId())): ?>
                        <small>
                        <?php foreach (Mage::helper('weee')->getApplied($_inquiry) as $tax): ?>
                            <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->displayPrices($tax['base_amount_incl_tax'], $tax['amount_incl_tax']); ?></span>
                        <?php endforeach; ?>
                        </small>
                    <?php endif; ?>

                    <?php if (Mage::helper('weee')->typeOfDisplay($_inquiry, 2, 'sales', $_inquiry->getStoreId())): ?>
                        <br />
                        <span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br />
                        <?php
                        echo $this->displayPrices(
                            $_inquiry->getBasePrice()+$_inquiry->getBaseWeeeTaxAppliedAmount()+$_inquiry->getBaseWeeeTaxDisposition(),
                            $_inquiry->getPrice()+$_inquiry->getWeeeTaxAppliedAmount()+$_inquiry->getWeeeTaxDisposition()
                        );
                        ?>
                        </span>
                    <?php endif; ?>
                <?php endif; ?>
            </span>
            <br />
        <?php endif; ?>
        <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceInclTax()): ?>
            <span class="price-incl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                    <span class="label"><?php echo $this->__('Incl. Tax'); ?>:</span>
                <?php endif; ?>
                <?php $_incl = $this->helper('checkout')->getPriceInclTax($_inquiry); ?>
                <?php $_baseIncl = $this->helper('checkout')->getBasePriceInclTax($_inquiry); ?>

                <?php if (Mage::helper('weee')->typeOfDisplay($_inquiry, array(0, 1, 4), 'sales', $_inquiry->getStoreId())): ?>
                    <?php echo $this->displayPrices($_baseIncl+$_inquiry->getBaseWeeeTaxAppliedAmount(), $_incl+$_inquiry->getWeeeTaxAppliedAmount()); ?>
                <?php else: ?>
                    <?php echo $this->displayPrices($_baseIncl-$_inquiry->getBaseWeeeTaxDisposition(), $_incl-$_inquiry->getWeeeTaxDisposition()) ?>
                <?php endif; ?>

                <?php if (Mage::helper('weee')->getApplied($_inquiry)): ?>
                    <br />
                    <?php if (Mage::helper('weee')->typeOfDisplay($_inquiry, 1, 'sales', $_inquiry->getStoreId())): ?>
                        <small>
                        <?php foreach (Mage::helper('weee')->getApplied($_inquiry) as $tax): ?>
                            <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->displayPrices($tax['base_amount'], $tax['amount']); ?></span>
                        <?php endforeach; ?>
                        </small>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_inquiry, 2, 'sales', $_inquiry->getStoreId())): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_inquiry) as $tax): ?>
                            <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $this->displayPrices($tax['base_amount_incl_tax'], $tax['amount_incl_tax']); ?></small></span>
                        <?php endforeach; ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_inquiry, 4, 'sales', $_inquiry->getStoreId())): ?>
                        <small>
                        <?php foreach (Mage::helper('weee')->getApplied($_inquiry) as $tax): ?>
                            <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->displayPrices($tax['base_amount_incl_tax'], $tax['amount_incl_tax']); ?></span>
                        <?php endforeach; ?>
                        </small>
                    <?php endif; ?>

                    <?php if (Mage::helper('weee')->typeOfDisplay($_inquiry, 2, 'sales', $_inquiry->getStoreId())): ?>
                        <br />
                        <span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $this->displayPrices($_baseIncl+$_inquiry->getBaseWeeeTaxAppliedAmount(), $_incl+$_inquiry->getWeeeTaxAppliedAmount()); ?></span>
                    <?php endif; ?>
                <?php endif; ?>
            </span>
        <?php endif; ?>

    </td>
    <td class="a-center">
        <?php echo $_inquiry->getQty()*1 ?>
    </td>
    <td class="a-center">
        <?php echo $_inquiry->getRetailer() ?>
    </td>    
    <td class="a-right">
        <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
            <span class="price-excl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                    <span class="label"><?php echo $this->__('Excl. Tax'); ?>:</span>
                <?php endif; ?>
           
                <?php if (Mage::helper('weee')->typeOfDisplay($_inquiry, array(0, 1, 4), 'sales')): ?>
                    <?php
                    echo $this->displayPrices(
                        $_inquiry->getBaseRowTotal()+$_inquiry->getBaseWeeeTaxAppliedRowAmount()+$_inquiry->getBaseWeeeTaxRowDisposition(),
                        $_inquiry->getRowTotal()+$_inquiry->getWeeeTaxAppliedRowAmount()+$_inquiry->getWeeeTaxRowDisposition()
                    );
                    ?>
                <?php else: ?>
                    <?php echo $this->displayPrices($_inquiry->getBaseRowTotal(), $_inquiry->getRowTotal()) ?>
                <?php endif; ?>
            
            
                <?php if (Mage::helper('weee')->getApplied($_inquiry)): ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_inquiry, 1, 'sales')): ?>
                        <small>
                        <?php foreach (Mage::helper('weee')->getApplied($_inquiry) as $tax): ?>
                            <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->displayPrices($tax['base_row_amount'], $tax['row_amount']); ?></span>
                        <?php endforeach; ?>
                        </small>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_inquiry, 2, 'sales')): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_inquiry) as $tax): ?>
                            <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $this->displayPrices($tax['base_row_amount_incl_tax'], $tax['row_amount_incl_tax']); ?></small></span>
                        <?php endforeach; ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_inquiry, 4, 'sales')): ?>
                        <small>
                        <?php foreach (Mage::helper('weee')->getApplied($_inquiry) as $tax): ?>
                            <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->displayPrices($tax['base_row_amount_incl_tax'], $tax['row_amount_incl_tax']); ?></span>
                        <?php endforeach; ?>
                        </small>
                    <?php endif; ?>
            
                    <?php if (Mage::helper('weee')->typeOfDisplay($_inquiry, 2, 'sales')): ?>
                        <br />
                        <span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br />
                        <?php
                        echo $this->displayPrices(
                            $_inquiry->getBaseRowTotal()+$_inquiry->getBaseWeeeTaxAppliedRowAmount()+$_inquiry->getBaseWeeeTaxRowDisposition(),
                            $_inquiry->getRowTotal()+$_inquiry->getWeeeTaxAppliedRowAmount()+$_inquiry->getWeeeTaxRowDisposition()
                        );
                        ?>
                        </span>
                    <?php endif; ?>
                <?php endif; ?>
            </span>
            <br />
        <?php endif; ?>
        <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceInclTax()): ?>
            <span class="price-incl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                    <span class="label"><?php echo $this->__('Incl. Tax'); ?>:</span>
                <?php endif; ?>
                <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_inquiry); ?>
                <?php $_baseIncl = $this->helper('checkout')->getBaseSubtotalInclTax($_inquiry); ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($_inquiry, array(0, 1, 4), 'sales')): ?>
                    <?php echo $this->displayPrices($_baseIncl+$_inquiry->getBaseWeeeTaxAppliedRowAmount(), $_incl+$_inquiry->getWeeeTaxAppliedRowAmount()); ?>
                <?php else: ?>
                    <?php echo $this->displayPrices($_baseIncl-$_inquiry->getBaseWeeeTaxRowDisposition(), $_incl-$_inquiry->getWeeeTaxRowDisposition()) ?>
                <?php endif; ?>
            
            
                <?php if (Mage::helper('weee')->getApplied($_inquiry)): ?>
            
                    <br />
                    <?php if (Mage::helper('weee')->typeOfDisplay($_inquiry, 1, 'sales')): ?>
                        <small>
                        <?php foreach (Mage::helper('weee')->getApplied($_inquiry) as $tax): ?>
                            <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->displayPrices($tax['base_row_amount'], $tax['row_amount']); ?></span>
                        <?php endforeach; ?>
                        </small>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_inquiry, 2, 'sales')): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_inquiry) as $tax): ?>
                            <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $this->displayPrices($tax['base_row_amount_incl_tax'], $tax['row_amount_incl_tax']); ?></small></span>
                        <?php endforeach; ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_inquiry, 4, 'sales')): ?>
                        <small>
                        <?php foreach (Mage::helper('weee')->getApplied($_inquiry) as $tax): ?>
                            <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->displayPrices($tax['base_row_amount_incl_tax'], $tax['row_amount_incl_tax']); ?></span>
                        <?php endforeach; ?>
                        </small>
                    <?php endif; ?>
            
                    <?php if (Mage::helper('weee')->typeOfDisplay($_inquiry, 2, 'sales')): ?>
                        <br /><span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $this->displayPrices($_baseIncl+$_inquiry->getBaseWeeeTaxAppliedRowAmount(), $_incl+$_inquiry->getWeeeTaxAppliedRowAmount()); ?></span>
                    <?php endif; ?>
                <?php endif; ?>
            </span>
        <?php endif; ?>
        </span>
    </td>
    <td class="a-right"><?php echo $this->displayPriceAttribute('tax_amount') ?></td>
    <td class="a-right"><?php echo $this->displayPriceAttribute('discount_amount') ?></td>
    <td class="a-right last">
        <?php echo $this->displayPrices(
            $_inquiry->getBaseRowTotal()+$_inquiry->getBaseTaxAmount()-$_inquiry->getBaseDiscountAmount()+$_inquiry->getBaseWeeeTaxAppliedRowAmount(),
            $_inquiry->getRowTotal()+$_inquiry->getTaxAmount()-$_inquiry->getDiscountAmount()+$_inquiry->getWeeeTaxAppliedRowAmount()
        ) ?>
    </td>
</tr>
